- name: Create jenkins directory
  file:
    path: /home/ubuntu/jenkins
    state: directory
    mode: '0755'
    owner: 1000
    group: 1000

- name : install jenkins
  docker_container:
    name : jenkins
    state : started
    cpus: 0.5
    memory: 800M
    image : jenkins/jenkins
    restart_policy: always
    privileged: yes
    user: '0'
    ports:
      - "8080:8080 "
      - "50000:50000"
    volumes:
      - "/home/ubuntu/jenkins:/var/jenkins_home"
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
    restart : yes
    # networks:
    #   - name : route
# - name : Setup nginx conf
#   template:
#     src : jenkins.conf.tpl
#     dest : /home/ubuntu/config/nginx/jenkins.conf