# Add HashiCorp GPG key
- name: Download and add HashiCorp GPG key
  ansible.builtin.shell: |
    wget -O- https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
  args:
    creates: /usr/share/keyrings/hashicorp-archive-keyring.gpg

# Add HashiCorp repository
- name: Add HashiCorp repository
  ansible.builtin.shell: |
    echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
  args:
    creates: /etc/apt/sources.list.d/hashicorp.list

# Update apt cache and install Terraform
- name: Update apt cache and install Terraform
  apt:
    update_cache: yes
    name: terraform
    state: present