- name: Install apt packages
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
    state: present

- name: Add Docker GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
    
# Add Docker repository
- name: Add Docker repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
    state: present

# Install Docker engine
- name: Install Docker engine
  apt:
    name: docker-ce
    state: present

# Add current user to the docker group
- name: Add current user to the docker group
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes
- name : chomd unix 
  shell : sudo chmod 666 /var/run/docker.sock
  
# Enable and start Docker service
- name: Enable and start Docker service
  systemd:
    name: docker
    enabled: yes
    state: started
